name: MicNet-env

channels:
  - conda-forge
  - defaults

dependencies:
  - bokeh==2.2.2
  - dask
  - h5py
  - hdf5
  - matplotlib-base
  - numba
  - pandas
  - pip 
  - pylint
  - python=3.8
  - scipy
  - spacy
  - hdbscan == 0.8.27
  
  - pip:
    - pyarrow
    - streamlit == 0.88.0
    - pytest
    - networkx
    - ipython
    - umap-learn == 0.5.1
    - python-louvain
    